Updates project to common catalog structure
brooklyncentral/brooklyn-etcd pull request #11
Opened 2017-04-03 16:39 UTC by m4rkmckenna

* Add karaf feature file

❌  Will break downstream classpath imports due to folder rename

2017-04-03 17:51 UTC, grkvlt requested changes
Looks good, only change is to copy icon file locally

2017-04-03 17:51 UTC, grkvlt commented on catalog/etcd/etcd.bom
> +  iconUrl: https://raw.githubusercontent.com/coreos/etcd/master/logos/etcd-stacked-color.png
see previous comment on icon

2017-04-03 17:51 UTC, grkvlt commented on catalog/etcd/catalog.bom
> +      iconUrl: https://raw.githubusercontent.com/coreos/etcd/master/logos/etcd-stacked-color.png
Can this file be copied to `resources/icons/etcd.png` in the repo, and referenced as a `classpath://` resource instead, to allow use when github access is not possible.

2017-04-03 18:14 UTC, m4rkmckenna commented
@grkvlt I put the etcd icon in the classpath

2017-04-04 12:02 UTC, Graeme-Miller approved these changes

2017-04-04 15:17 UTC, grkvlt approved these changes
Thanks @m4rkmckenna happy with this

2017-04-04 15:18 UTC, merged